- pkg:maven/com.sksamuel.hoplite/hoplite-micrometer-prometheus@2.3.0?classifier=sources
- pkg:maven/com.sksamuel.hoplite/hoplite-micrometer-prometheus@2.3.1?classifier=sources
- pkg:maven/com.sksamuel.hoplite/hoplite-micrometer-prometheus@2.3.2?classifier=sources
- pkg:maven/com.sksamuel.hoplite/hoplite-micrometer-prometheus@2.3.3?classifier=sources
- pkg:maven/com.sksamuel.hoplite/hoplite-micrometer-prometheus@2.4.0?classifier=sources
- pkg:maven/com.sksamuel.hoplite/hoplite-micrometer-prometheus@2.5.0?classifier=sources
- pkg:maven/com.sksamuel.hoplite/hoplite-micrometer-prometheus@2.5.1?classifier=sources
- pkg:maven/com.sksamuel.hoplite/hoplite-micrometer-prometheus@2.5.2?classifier=sources
- pkg:maven/com.sksamuel.hoplite/hoplite-micrometer-prometheus@2.6.0?classifier=sources
- pkg:maven/com.sksamuel.hoplite/hoplite-micrometer-prometheus@2.6.1?classifier=sources
- pkg:maven/com.sksamuel.hoplite/hoplite-micrometer-prometheus@2.6.2?classifier=sources
- pkg:maven/com.sksamuel.hoplite/hoplite-micrometer-prometheus@2.6.3?classifier=sources
- pkg:maven/com.sksamuel.hoplite/hoplite-micrometer-prometheus@2.6.4?classifier=sources
- pkg:maven/com.sksamuel.hoplite/hoplite-micrometer-prometheus@2.6.5?classifier=sources
- pkg:maven/com.sksamuel.hoplite/hoplite-micrometer-prometheus@2.7.0?classifier=sources
- pkg:maven/com.sksamuel.hoplite/hoplite-micrometer-prometheus@2.7.1?classifier=sources
- pkg:maven/com.sksamuel.hoplite/hoplite-micrometer-prometheus@2.7.2?classifier=sources
- pkg:maven/com.sksamuel.hoplite/hoplite-micrometer-prometheus@2.7.3?classifier=sources
- pkg:maven/com.sksamuel.hoplite/hoplite-micrometer-prometheus@2.7.4?classifier=sources
- pkg:maven/com.sksamuel.hoplite/hoplite-micrometer-prometheus@2.8.0.RC1?classifier=sources
