- pkg:maven/com.sksamuel.hoplite/hoplite-micrometer-prometheus@2.3.0?classifier=sources
- pkg:maven/com.sksamuel.hoplite/hoplite-micrometer-prometheus@2.3.1?classifier=sources
- pkg:maven/com.sksamuel.hoplite/hoplite-micrometer-prometheus@2.3.2?classifier=sources
- pkg:maven/com.sksamuel.hoplite/hoplite-micrometer-prometheus@2.3.3?classifier=sources
- pkg:maven/com.sksamuel.hoplite/hoplite-micrometer-prometheus@2.4.0?classifier=sources
