- pkg:maven/com.github.fmjsjx/libcommon-prometheus@2.9.0-RC1?classifier=sources
- pkg:maven/com.github.fmjsjx/libcommon-prometheus@2.9.0-RC2?classifier=sources
- pkg:maven/com.github.fmjsjx/libcommon-prometheus@2.9.0?classifier=sources
- pkg:maven/com.github.fmjsjx/libcommon-prometheus@3.0.0-RC1?classifier=sources
- pkg:maven/com.github.fmjsjx/libcommon-prometheus@3.0.0?classifier=sources
