- pkg:maven/com.github.shootmoon/xmlconfigmapper-processor@0.1.2
- pkg:maven/com.github.shootmoon/xmlconfigmapper-processor@0.1.2?classifier=sources
- pkg:maven/com.github.shootmoon/xmlconfigmapper-processor@0.2.0
- pkg:maven/com.github.shootmoon/xmlconfigmapper-processor@0.2.0?classifier=sources
