- pkg:maven/net.sf.ebus/config@5.0.0
- pkg:maven/net.sf.ebus/config@5.0.0?classifier=sources
- pkg:maven/net.sf.ebus/config@5.0.1
- pkg:maven/net.sf.ebus/config@5.0.1?classifier=sources
- pkg:maven/net.sf.ebus/config@5.1.0
- pkg:maven/net.sf.ebus/config@5.1.0?classifier=sources
- pkg:maven/net.sf.ebus/config@5.2.0
- pkg:maven/net.sf.ebus/config@5.2.0?classifier=sources
- pkg:maven/net.sf.ebus/config@5.2.1
- pkg:maven/net.sf.ebus/config@5.2.1?classifier=sources
