- pkg:maven/com.admin4j.framework/prometheus-spring-boot-starter@0.8.0
- pkg:maven/com.admin4j.framework/prometheus-spring-boot-starter@0.8.0?classifier=sources
- pkg:maven/com.admin4j.framework/prometheus-spring-boot-starter@0.9.5
- pkg:maven/com.admin4j.framework/prometheus-spring-boot-starter@0.9.5?classifier=sources
