- pkg:maven/dev.travisbrown/sized-core_2.13@0.1.0
- pkg:maven/dev.travisbrown/sized-core_2.13@0.1.0?classifier=sources
- pkg:maven/dev.travisbrown/sized-core_2.13@0.2.0
- pkg:maven/dev.travisbrown/sized-core_2.13@0.2.0?classifier=sources
