- pkg:maven/org.apache.seatunnel/connector-prometheus@2.3.10
- pkg:maven/org.apache.seatunnel/connector-prometheus@2.3.10?classifier=sources
- pkg:maven/org.apache.seatunnel/connector-prometheus@2.3.11
- pkg:maven/org.apache.seatunnel/connector-prometheus@2.3.11?classifier=sources
- pkg:maven/org.apache.seatunnel/connector-prometheus@2.3.9
- pkg:maven/org.apache.seatunnel/connector-prometheus@2.3.9?classifier=sources
