- pkg:maven/com.permutive/prometheus4cats-contrib-opencensus_2.12@0.1.4
- pkg:maven/com.permutive/prometheus4cats-contrib-opencensus_2.12@0.1.4?classifier=sources
- pkg:maven/com.permutive/prometheus4cats-contrib-opencensus_2.12@0.2.0
- pkg:maven/com.permutive/prometheus4cats-contrib-opencensus_2.12@0.2.0?classifier=sources
- pkg:maven/com.permutive/prometheus4cats-contrib-opencensus_2.12@0.2.1
- pkg:maven/com.permutive/prometheus4cats-contrib-opencensus_2.12@0.2.1?classifier=sources
- pkg:maven/com.permutive/prometheus4cats-contrib-opencensus_2.12@0.3.0
- pkg:maven/com.permutive/prometheus4cats-contrib-opencensus_2.12@0.3.0?classifier=sources
- pkg:maven/com.permutive/prometheus4cats-contrib-opencensus_2.12@1.0.0
- pkg:maven/com.permutive/prometheus4cats-contrib-opencensus_2.12@1.0.0?classifier=sources
- pkg:maven/com.permutive/prometheus4cats-contrib-opencensus_2.12@2.0.0
- pkg:maven/com.permutive/prometheus4cats-contrib-opencensus_2.12@2.0.0-RC1
- pkg:maven/com.permutive/prometheus4cats-contrib-opencensus_2.12@2.0.0-RC1?classifier=sources
- pkg:maven/com.permutive/prometheus4cats-contrib-opencensus_2.12@2.0.0-RC2
- pkg:maven/com.permutive/prometheus4cats-contrib-opencensus_2.12@2.0.0-RC2?classifier=sources
- pkg:maven/com.permutive/prometheus4cats-contrib-opencensus_2.12@2.0.0?classifier=sources
- pkg:maven/com.permutive/prometheus4cats-contrib-opencensus_2.12@2.1.0
- pkg:maven/com.permutive/prometheus4cats-contrib-opencensus_2.12@2.1.0?classifier=sources
