- pkg:maven/com.permutive/prometheus4cats-contrib-opencensus_2.12@0.1.4
- pkg:maven/com.permutive/prometheus4cats-contrib-opencensus_2.12@0.1.4?classifier=sources
- pkg:maven/com.permutive/prometheus4cats-contrib-opencensus_2.12@0.2.0
- pkg:maven/com.permutive/prometheus4cats-contrib-opencensus_2.12@0.2.0?classifier=sources
