- pkg:maven/dev.travisbrown/scalactic_0.22@3.1.0-20200123-9982f0d-NIGHTLY
- pkg:maven/dev.travisbrown/scalactic_0.22@3.1.0-20200123-9982f0d-NIGHTLY?classifier=sources
- pkg:maven/dev.travisbrown/scalactic_0.22@3.1.0-20200201-c4c847f-NIGHTLY
- pkg:maven/dev.travisbrown/scalactic_0.22@3.1.0-20200201-c4c847f-NIGHTLY?classifier=sources
