- pkg:maven/org.kie/kie-addons-monitoring-prometheus@10.0.0
- pkg:maven/org.kie/kie-addons-monitoring-prometheus@10.0.0?classifier=sources
- pkg:maven/org.kie/kie-addons-monitoring-prometheus@10.1.0
- pkg:maven/org.kie/kie-addons-monitoring-prometheus@10.1.0?classifier=sources
