- pkg:maven/io.prometheus.jmx/collector@0.3
- pkg:maven/io.prometheus.jmx/collector@0.3?classifier=sources
- pkg:maven/io.prometheus.jmx/collector@0.4
- pkg:maven/io.prometheus.jmx/collector@0.4?classifier=sources
- pkg:maven/io.prometheus.jmx/collector@0.5
- pkg:maven/io.prometheus.jmx/collector@0.5?classifier=sources
